TicTacToe Game Project
Samitti/Tic-Tac-Toe-Project pull request #3
Opened 2020-09-16 08:09 UTC by Mupa1

## TicTacToe Game Project

In this project, we made all changes requested by the TSE. We:-
- Divided the project into 3modules
- Separated the game logic from the dom manipulation
- Removed the numbers from the cell

Kindly review our project

2020-09-16 08:54 UTC, mikenath223 requested changes
### Hi Team. 👋

**One has to love the frontend. This is neat.👌🚀**

However, let's fix this:

- [ ] Oh my there is no package.json in your project. It is very important to have a package.json. How does a user start your project? Please include it.

- [ ] Please add `Getting started` section to your readme.

**### There are other comments made on your code please  check and fix them.**

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-09-16 08:56 UTC, mikenath223 commented on index.js
> +    alertMsg.innerHTML = msg;
- [ ] This still counts as DOM manipulation. Please move this to dom.js, along with other similar code lines.

2020-09-16 08:58 UTC, mikenath223 commented on index.js
> +      gameOver.style.display = 'block';
- [ ] All styles should be in the CSS file and then the dom should be manipulated by togling a classlist on dom.js.

2020-09-17 09:50 UTC, Samitti commented
Hi, we have made the changes requested from previous review. Kindly review our code. 
-  added the package.json file.
- separated the dom manipulation from the game logic. 
- added the getting started section on the README.

2020-09-17 09:55 UTC, rOluochKe approved these changes
### Well done, you got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-09-17 09:59 UTC, merged